# Generated by Django 4.0 on 2021-12-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromdetails',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fromdetails',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fromdetails',
            name='stream',
            field=models.CharField(max_length=30),
        ),
    ]
